# -*- coding: utf-8 -*-
"""where is number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p82k5BQthQihfklOJzo_fixQBaptG1Pg
"""

import random

def ryss(L):
  for i in range(len(L)-1):
    _min = i
    for j in range(i+1,len(L)):
      if L[_min] > L[j]:
        _min = j
    L[i],L[_min] = L[_min],L[i]

def rybs(L,num,start):
  if len(L) == 0: return None
  mid = len(L)//2
  if L[mid] > num:
    comp = L[:mid]
    return rybs(comp,num,start)
  elif L[mid] < num:
    start = mid + 1 ; comp = L[mid+1:]
    return rybs(comp,num,start)
  else:
    return start + mid
    
def result():
  num_10 = []
  while True:
    num = random.randint(1,100)
    if num_10.count(num) == 0:
      num_10.append(num)
    if len(num_10) == 10: break

  find_num = num_10[3]

  try:
    loc = int(input(f'{find_num}가 있는 곳의 번호 입력: '))
  except:
    print('1부터 10까지의 숫자만 입력하세요.')
  else:
    if loc > 10 or loc < 1:
      print('1부터 10까지의 숫자만 입력하세요.')
    else:
      ryss(num_10)
      real_loc = rybs(num_10,find_num,0)+1

      res = ''
      if loc == real_loc:
        res = '일치'
      else:
        res = f'불일치 / 위치: {real_loc}'
      return res

def final(r):
  if r == '일치':
      money[user] += 100
      print(f'일치 / 돈: {money[user]}')
  else:
      money[user] -= 100
      print(f'{r} / 돈: {money[user]}')

money = {}
name = []

print('''<<<숫자 찾기 게임>>>
- user name은 영어로 입력해주시기 바랍니다.
- 1000coin이 기본으로 제공되며 이를 다 소진할 시 게임을 할 수 없습니다.
- 이긴다면 100coin을 얻고, 진다면 100coin을 잃게 됩니다.
- 1~10의 위치 중 주어진 숫자의 위치를 추측해서 입력해주시면 됩니다. 
- 종료 후 재접속 시 모든 데이터는 초기화됩니다.
''' )


while True:
  user = input('name: ')
  if user.isalpha() == False:
    print('영어로 입력해주세요.')
    continue
  elif user.upper() == user.lower():
    print('영어로 입력해주세요.')
    continue
  else:
    if user in ['q','Q']: break

    if user in name:
      s = result()
      final(s)
      if money[user] == 0: break  
    else:
      name.append(user)
      money[user] = 1000
      s = result()
      final(s)

print()